SELECT * FROM ACT_PRG_TO_MSG WHERE MSG_ID = 73938;

SELECT * FROM ACT_PRG_TO_MSG WHERE PROGRAM_ID = 7401;

SELECT * FROM ACT_DAM WHERE DAM_ID = 70663;

SELECT * FROM ACT_MSG_TO_ELEMENT WHERE D710_ID LIKE 'NUMBER_1';

SELECT * FROM ACT_MSG_TO_ELEMENT WHERE MSG_ID = 62854;

SELECT * FROM ACT_PRG_TO_MSG WHERE MSG_ID = 62854;

SELECT * FROM ACT_PRG_TO_MSG WHERE PROGRAM_ID = 5550;

SELECT * FROM ACT_ELEMENT;