SELECT *
FROM ARBOR.Z_TBI_IMP_CREDITO_BACKLOG
ORDER BY CONTA_FATURA;

UPDATE ARBOR.Z_TBI_IMP_CREDITO_BACKLOG
SET FL_AGENDA = 0
WHERE FL_AGENDA = 1;
COMMIT;

SELECT * FROM PARAMETROS_PREPAGAMENTO
WHERE EXTERNAL_ID LIKE '%2146767496%'
OR EXTERNAL_ID LIKE '%2384065091%';

DELETE FROM PARAMETROS_PREPAGAMENTO
WHERE EXTERNAL_ID LIKE '%2146767496%'
OR EXTERNAL_ID LIKE '%2384065091%';
COMMIT;

SELECT
  CONTA_FATURA,
  TIPO_CONTA_FATURA,
  SUM(VL_CREDITO),
  TO_CHAR(DATA_EMISSAO, 'MM/YY'),
  OPEN_ITEM_ID,
  FL_AGENDA
FROM
  ARBOR.Z_TBI_IMP_CREDITO_BACKLOG
WHERE
  CICLO = 'ST'
  AND MOD(DBMS_ROWID.ROWID_BLOCK_NUMBER(ROWID), 1) + 1 = 1
  --AND FL_AGENDA = 0
GROUP BY
  CONTA_FATURA,
  TIPO_CONTA_FATURA,
  TO_CHAR(DATA_EMISSAO, 'MM/YY'),
  FL_AGENDA,
  OPEN_ITEM_ID
ORDER BY CONTA_FATURA;
