SELECT COUNT(1)
FROM TBI_IMP_CREDITO_POSTUMO;

SELECT *
FROM TBI_IMP_CREDITO_POSTUMO;

SELECT *
FROM PARAMETROS_PREPAGAMENTO
WHERE
  EXTERNAL_ID LIKE '%2146767496%'
  OR EXTERNAL_ID LIKE '%2343501045%'
  OR EXTERNAL_ID LIKE '%2383017062%'
  OR EXTERNAL_ID LIKE '%2384065091%'
  OR EXTERNAL_ID LIKE '%2572677611%'
  OR EXTERNAL_ID LIKE '%2799342631%'
  OR EXTERNAL_ID LIKE '%2954962014%'
ORDER BY EXTERNAL_ID;

SELECT *
FROM EXTERNAL_ID_ACCT_MAP
WHERE
  EXTERNAL_ID LIKE '%2146767496%'
  OR EXTERNAL_ID LIKE '%2343501045%'
  OR EXTERNAL_ID LIKE '%2383017062%'
  OR EXTERNAL_ID LIKE '%2384065091%'
  OR EXTERNAL_ID LIKE '%2572677611%'
  OR EXTERNAL_ID LIKE '%2799342631%'
  OR EXTERNAL_ID LIKE '%2954962014%'
ORDER BY EXTERNAL_ID;

SELECT PP.EXTERNAL_ID,
  PP.EXTERNAL_ID_TYPE,
  'ST' CICLO,
  SUM(PP.VALOR_PREPAGAMENTO) TOT_CREDITO,
  SUM(
  CASE
    WHEN OPEN_ITEM_ID = 90
    THEN PP.VALOR_PREPAGAMENTO
    ELSE 0
  END ) TOT_CRED_90,
  SUM(
  CASE
    WHEN OPEN_ITEM_ID = 10
    THEN PP.VALOR_PREPAGAMENTO
    ELSE 0
  END) TOT_CRED_10,
  PP.ROWID PP_ROWID,
  EIAM.ROWID EIAM_ROWID
FROM PARAMETROS_PREPAGAMENTO PP,
  EXTERNAL_ID_ACCT_MAP EIAM
WHERE TRIM(PP.EXTERNAL_ID)  = EIAM.EXTERNAL_ID
AND PP.EXTERNAL_ID_TYPE   = EIAM.EXTERNAL_ID_TYPE
AND EIAM.EXTERNAL_ID_TYPE = 14
AND PP.OPEN_ITEM_ID      IN (90, 10)
AND EIAM.SERVER_ID        = 1
--AND TRIM(PP.OBSERVACOES) LIKE '%PRJ 2867 SUB 1954 - Créditos concedidos devido à redução de alíquota para o AM.%'
AND PP.OBSERVACOES = 'PRJ 2867 SUB 1954 - Créditos concedidos devido à redução de alíquota para o AM.'
AND EXISTS
  (SELECT 1
  FROM ARBOR.Z_TBI_IMP_CREDITO_BACKLOG TICB
  WHERE PP.EXTERNAL_ID    = TICB.CONTA_FATURA
  AND PP.EXTERNAL_ID_TYPE = TICB.TIPO_CONTA_FATURA
  AND PP.OPEN_ITEM_ID     = TICB.OPEN_ITEM_ID
  AND CICLO               = 'ST'
  )
GROUP BY PP.EXTERNAL_ID,
  PP.EXTERNAL_ID_TYPE,
  'ST',
  PP.ROWID,
  EIAM.ROWID;

