SET SERVEROUTPUT ON

DECLARE
  CURSOR CUR_CREDITO IS
  SELECT
    OIF.EXTERNAL_ID_ACCOUNT,
    OIF.EXTERNAL_ID_TYPE_ACCT,
    DECODE(SUBSTR(OIF.BILL_PERIOD, 1, 1), 'Q', 'QR', 'R', 'QR', 'S', 'ST', 'T', 'ST', 'U', 'UV', 'V', 'UV') CICLO,
    OIF.ACCOUNT_NO,
    OIF.BILL_REF_NO,
    OIF.BILL_REF_RESETS,
    TO_CHAR(OIF.STATEMENT_DATE, 'YYYYMMDDHH24MISS') STATEMENT_DATE,
    OIDF.TYPE_CODE,
    OIDF.SUBTYPE_CODE,
    OIDF.DESCRIPTION,
    SUM((OIDF.AMOUNT + OIDF.DISCOUNT)) VL_FATURADO,
    ROUND(((OIDF.AMOUNT + OIDF.DISCOUNT) * 0.1309758), 2) VL_CREDITO,
    OIDF.OPEN_ITEM_ID,
    OIDF.EXTERNAL_ID,
    OIDF.EXTERNAL_ID_TYPE,
    OIF.ROWID OIF_ROWID,
    OIDF.ROWID OIDF_ROWID
  FROM
    TMP_OIBIF_FATURA_IMP OIF,
    TMP_OIBIF_DETALHE_FATURA_IMP OIDF
  WHERE
    OIF.MKT_CODE = 24
    AND OIF.BACKOUT_STATUS = 0
    AND OIDF.OPEN_ITEM_ID IN (10, 90)
    AND OIF.BILL_REF_NO = OIDF.BILL_REF_NO
    AND OIF.BILL_REF_RESETS = OIDF.BILL_REF_RESETS
    AND OIDF.EXTERNAL_ID IS NOT NULL
    AND OIDF.EXTERNAL_ID_TYPE IS NOT NULL
  GROUP BY
    OIF.EXTERNAL_ID_ACCOUNT,
    OIF.EXTERNAL_ID_TYPE_ACCT,
    DECODE(SUBSTR(OIF.BILL_PERIOD, 1, 1), 'Q', 'QR', 'R', 'QR', 'S', 'ST', 'T', 'ST', 'U', 'UV', 'V', 'UV'),
    OIF.ACCOUNT_NO,
    OIF.BILL_REF_NO,
    OIF.BILL_REF_RESETS,
    TO_CHAR(OIF.STATEMENT_DATE, 'YYYYMMDDHH24MISS'),
    OIDF.TYPE_CODE,
    OIDF.SUBTYPE_CODE,
    OIDF.DESCRIPTION,
    ROUND(((OIDF.AMOUNT + OIDF.DISCOUNT) * 0.1309758), 2),
    OIDF.OPEN_ITEM_ID,
    OIDF.EXTERNAL_ID,
    OIDF.EXTERNAL_ID_TYPE,
    OIF.ROWID,
    OIDF.ROWID
  HAVING SUM((OIDF.AMOUNT + OIDF.DISCOUNT)) > 0;

BEGIN

  FOR item IN CUR_CREDITO LOOP
  
    INSERT INTO TBI_IMP_CREDITO_BACKLOG (
      CONTA_FATURA,
      TIPO_CONTA_FATURA,
      CICLO,
      NUM_FATURA,
      NUM_EXT_FATURA,
      DATA_EMISSAO,
      TIPO_ELEMENTO,
      COD_ELEMENTO,
      DESCRICAO_ELEMENTO,
      VL_FATURADO,
      VL_CREDITO,
      OPEN_ITEM_ID,
      DATA_PROCESSAMENTO,
      EXTERNAL_ID,
      EXTERNAL_ID_TYPE,
      FL_AGENDA
    )
    VALUES (
      item.EXTERNAL_ID_ACCOUNT,
      item.EXTERNAL_ID_TYPE_ACCT,
      item.CICLO,
      item.BILL_REF_NO,
      item.BILL_REF_RESETS,
      TO_DATE(item.STATEMENT_DATE, 'YYYYMMDDHH24MISS'),
      item.TYPE_CODE,
      item.SUBTYPE_CODE,
      item.DESCRIPTION,
      item.VL_FATURADO,
      item.VL_CREDITO,
      item.OPEN_ITEM_ID,
      SYSDATE,
      item.EXTERNAL_ID,
      item.EXTERNAL_ID_TYPE,
      0
    );

    --dbms_output.put_line('EXTERNAL_ID_ACCOUNT = ');
  END LOOP;
  
  COMMIT;
  
END;
/