SET SERVEROUTPUT ON
DECLARE
  MYSTRING VARCHAR(100) := 'PRJ9765';
  MYSQL LONG;
BEGIN
  DBMS_OUTPUT.PUT_LINE('Procurando texto "'||MYSTRING||'"');
  FOR REG IN (
    SELECT SQL_TEXT, DAM_ID FROM ACT_DAM WHERE DAM_ID IN (70663)
  )
  LOOP
    MYSQL := REG.SQL_TEXT;
    IF INSTR(UPPER(MYSQL), UPPER(MYSTRING)) <> 0 THEN
      DBMS_OUTPUT.PUT_LINE('Em DAM_ID '||REG.DAM_ID||' : ENCONTRADO');
    ELSE
      DBMS_OUTPUT.PUT_LINE('Em DAM_ID '||REG.DAM_ID||' : NÃO ENCONTRADO');
    END IF;
  END LOOP;
END;
/
